package constants;

import ui.Minigame;

public class MinigameConstants {

    public static final Minigame[] MARIO_PARTY_1_MINIGAMES = {
            new Minigame(0x00, "Memory Match", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x02, "Slot Machine", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x03, "Buried Treasure", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x04, "Treasure Divers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "Shell Game", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x06, "Slot Car Derby 1", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x07, "Hot Bob-omb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x08, "Slot Car Derby 2", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x09, "Pipe Maze", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x0A, "Ghost Guess", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x0B, "Musical Mushroom", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0C, "Pedal Power", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x0D, "Crazy Cutter", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0E, "Face Lift", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0F, "Whack-a-Plant", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x10, "Bash 'n' Cash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Bowl Over", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Ground Pound", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x13, "Balloon Burst", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x14, "Coin Block Blitz", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x15, "Coin Block Bash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Skateboard Scamper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x17, "Box Mountain Mayhem", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x18, "Platform Peril", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x19, "Teetering Towers", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x1A, "Mushroom Mix-Up", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1B, "Bumper Ball Maze 1", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x1C, "Grab Bag", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1D, "Bobsled Run", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1E, "Bumper Balls", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1F, "TightRope Treachery", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x20, "Knock Block Tower", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x21, "Tipsy Tourney", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x22, "Bombs Away", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x23, "Crane Game", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x24, "Bumper Ball Maze 2", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x25, "Slot Car Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x26, "Mario Bandstand", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x27, "Desert Dash", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x28, "Shy Guy Says", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x29, "Limbo Dance", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x2A, "Bombsketball", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2B, "Cast Aways", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2C, "Key-pa-Way", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2D, "Running of the Bulb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2E, "Hot Rope Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2F, "Handcar Havoc", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x31, "Deep Sea Divers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x32, "Piranha's Pursuit", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x33, "Tug o' War", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x34, "Paddle Battle", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x35, "Bumper Ball Maze 3", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x36, "Coin Shower Flower", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x37, "Hammer Drop", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_2_MINIGAMES = {
            new Minigame(0x01, "BOWSER Slots", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x02, "Roll Out the Barrels", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x03, "Coffin Congestion", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x04, "Hammer Slammer", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x05, "Give Me a Brake!", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x06, "Mallet-Go Round", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x07, "Grab Bag", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x08, "Bumper Balloon Cars", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x09, "Rakin' 'em In", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0B, "Day at the Races", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0C, "Face Lift", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0D, "Crazy Cutters", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0E, "Hot BOB-OMB", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0F, "Bowl Over", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x10, "Rainbow Run", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Crane Game", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Move to the Music", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x13, "BOB-OMB Barrage", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x14, "Look Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x15, "Shock Drop or Roll", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Lights Out", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x17, "Filet Relay", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x18, "Archer-ival", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1A, "TOAD Bandstand", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1B, "Bobsled Run", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1C, "Handcar Havoc", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1E, "Balloon Burst", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1F, "Sky Pilots", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x20, "Speed Hockey", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x21, "Cake Factory", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x23, "Dungeon Dash", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x24, "Magnet Carta", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x25, "Lava Tile Isle", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x26, "Hot Rope Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x27, "Shell Shocked", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x28, "TOAD in the Box", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x29, "Mecha-Marathon", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2A, "Roll Call", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2B, "Abandon Ship", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2C, "Platform Peril", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2D, "Totem Pole Pound", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2E, "Bumper Balls", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x30, "Bombs Away", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x31, "Tipsy Tourney", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x32, "Honeycomb Havoc", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x33, "Hexagon Heat", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x34, "Skateboard Scamper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x35, "Slot Car Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x36, "Shy Guy Says", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x37, "Sneak 'n' Snore", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x39, "Driver's Ed", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x3B, "Quick Draw Corks", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3C, "Saber Slashes", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3D, "Mushroom Brew", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3E, "Time Bomb", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3F, "Psychic Safari", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x40, "Rock Paper MARIO", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x41, "BOWSER's Big Blast", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x42, "Looney Lumberjacks", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x43, "Torpedo Targets", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x44, "Destruction Duet", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x45, "Dizzy Dancing", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x46, "Tile Driver", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x47, "Quicksand Cache", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x48, "Deep Sea Salvage", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_3_MINIGAMES = {
            new Minigame(0x01, "Hand, Line and Sinker", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x02, "Coconut Conk", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x03, "Spotlight Swim", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x04, "Boulder Ball", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x05, "Crazy Cogs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x06, "Hide and Sneak", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x07, "Ridiculous Relay", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x08, "Thwomp Pull", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x09, "River Raiders", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x0A, "Tidal Toss", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x0B, "Eatsa Pizza", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0C, "Baby Bowser Broadside", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0D, "Pump, Pump and Away", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0E, "Hyper Hydrants", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0F, "Picking Panic", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x10, "Cosmic Coaster", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x11, "Puddle Paddle", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x12, "Etch 'n' Catch", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x13, "Log Jam", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x14, "Slot Synch", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x15, "Treadmill Grill", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x16, "Toadstool Titan", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x17, "Aces High", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x18, "Bounce 'n' Trounce", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x19, "Ice Rink Risk", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1A, "Locked Out", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x1B, "Chip Shot Challenge", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1C, "Parasol Plummet", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1D, "Messy Memory", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1E, "Picture Imperfect", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1F, "Mario's Puzzle Party", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x20, "The Beat Goes On", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x21, "M.P.I.Q.", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x22, "Curtain Call", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x23, "Water Whirled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x24, "Frigid Bridges", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x25, "Awful Tower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x26, "Cheep Cheep Chase", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x27, "Pipe Cleaners", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x28, "Snowball Summit", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x29, "All Fired Up", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2A, "Stacked Deck", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2B, "Three Door Monty", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2C, "Rockin' Raceway", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2D, "Merry-Go-Chomp", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2E, "Slap Down", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2F, "Storm Chasers", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x30, "Eye Sore", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x31, "Vine With Me", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x32, "Popgun Pick-Off", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x33, "End of the Line", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x34, "Bowser Toss", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x35, "Baby Bowser Bonkers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x36, "Motor Rooter", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x37, "Silly Screws", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x38, "Crowd Cover", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x39, "Tick Tock Hop", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3A, "Fowl Play", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3B, "Winner's Wheel", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3C, "Hey, Batter, Batter!", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3D, "Bobbing Bow-loons", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3E, "Dorrie Dip", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3F, "Swinging with Sharks", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x40, "Swing 'n' Swipe", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x42, "Stardust Battle", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x43, "Game Guy's Roulette", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x44, "Game Guy's Lucky 7", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x45, "Game Guy's Magic Boxes", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x46, "Game Guy's Sweet Surprise", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x47, "Dizzy Dinghies", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x48, "Mario's Puzzle Party Pro", MinigameCategoryConstants.EXTRA_MINIGAME),
    };

    public static final Minigame[] MARIO_PARTY_4_MINIGAMES = {
            new Minigame(1, "Manta Rings", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Slime Time", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Booksquirm", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Trace Race", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(5, "Mario Medley", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Avalanche!", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Domination", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Paratrooper Plunge", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Toad's Quick Draw", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Three Throw", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Photo Finish", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Mr. Blizzard's Brigade", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Bob-Omb Breakers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Long Claw of the Law", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Stamp Out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Candlelight Flight", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(17, "Makin' Waves", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(18, "Hide and Go BOOM!", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(19, "Tree Stomp", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(20, "Fish n' Drips", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(21, "Hop or Pop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(22, "Money Belts", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "GOOOOOOOAL!!", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Blame it on the Crane", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(25, "The Great Deflate", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(26, "Revers-a-Bomb", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(27, "Right Oar Left?", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(28, "Cliffhangers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(29, "Team Treasure Trek", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(30, "Pair-a-Sailing", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(31, "Order Up", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(32, "Dungeon Duos", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(33, "Beach Volley Folly", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(34, "Cheep Cheep Sweep", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Darts of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(36, "Fruits of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(37, "Balloon of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(38, "Chain Chomp Fever", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(39, "Paths of Peril", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(40, "Bowser's Bigger Blast", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(41, "Butterfly Blitz", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(43, "Mario Speedwagons", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(45, "Bowser Bop", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(46, "Mystic Match 'Em", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(47, "Archaeologuess", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(48, "Goomba's Chip Flip", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(49, "Kareening Koopas", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(50, "The Final Battle!", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(55, "Rumble Fishing", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(56, "Take a Breather", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(57, "Bowser Wrestling", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(58, "Panels of Doom", MinigameCategoryConstants.EXTRA_MINIGAME),
    };

    public static final Minigame[] MARIO_PARTY_5_MINIGAMES = {
            new Minigame(1, "Coney Island", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Ground Pound Down", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Chimp Chase", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Chomp Romp", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Pushy Penguins", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Leaf Leap", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Night Light Fright", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Pop-Star Piranhas", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Mazed & Confused", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Dinger Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Hydrostars", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Later Skater", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Will Flower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Triple Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Hotel Goomba", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Coin Cache", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(17, "Flatiator", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(18, "Squared Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(19, "Mario Mechs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(20, "Revolving Fire", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(21, "Clock Stoppers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(22, "Heat Stroke", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "Beam Team", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Vicious Vending", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(25, "Big Top Drop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(26, "Defuse or Lose", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(27, "ID UFO", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(28, "Mario Can-Can", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(29, "Handy Hoppers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(30, "Berry Basket", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(31, "Bus Buffer", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(32, "Rumble Ready", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(33, "Submarathon", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(34, "Manic Mallets", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Astro-Logical", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(36, "Bill Blasters", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(37, "Tug-o-Dorrie", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(38, "Twist 'n' Out", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(39, "Lucky Lineup", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(40, "Random Ride", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(41, "Shock Absorbers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(42, "Countdown Pound", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(43, "Whomp Maze", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(44, "Shy Guy Showdown", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(45, "Button Mashers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(46, "Get a Rope", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(47, "Pump 'n' Jump", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(48, "Head Waiter", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(49, "Blown Away", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(50, "Merry Poppings", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(51, "Pound Peril", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Piece Out", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(53, "Bound of Music", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(54, "Wind Wavers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Sky Survivor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Rain of Fire", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(60, "Cage-in Cookin'", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(61, "Scaldin' Cauldron", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(62, "Frightmare", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(63, "Flower Shower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(64, "Dodge Bomb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(65, "Fish Upon a Star", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(66, "Rumble Fumble", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(67, "Quilt for Speed", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(68, "Tube It or Lose It", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(69, "Mathletes", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(70, "Fight Cards", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(71, "Banana Punch", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(72, "Da Vine Climb", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(73, "Mass A-peel", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(74, "Panic Pinball", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(75, "Banking Coins", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(76, "Frozen Frenzy", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(77, "Curvy Curbs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(78, "Beach Volleyball", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(79, "Fish Sticks", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(80, "Ice Hockey", MinigameCategoryConstants.EXTRA_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_6_MINIGAMES = {
            new Minigame(1, "Smashdance", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Odd Card Out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Freeze Frame", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "What Goes Up...", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Granite Getaway", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Circuit Maximus", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Catch You Letter", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Snow Whirled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Daft Rafts", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Tricky Tires", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Treasure Trawlers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Memory Lane", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Mowtown", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Cannonball Fun", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Note to Self", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Same is Lame", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(17, "Light Up My Night", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(18, "Lift Leapers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(19, "Blooper Scooper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(20, "Trap Ease Artist", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(21, "Pokey Punch-out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(22, "Money Belt", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(23, "Cash Flow", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Cog Jog", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(25, "Sink or Swim", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(26, "Snow Brawl", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(27, "Ball Dozers", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(28, "Surge and Destroy", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(29, "Pop Star", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(30, "Stage Fright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(31, "Conveyor Bolt", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(32, "Crate and Peril", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(33, "Ray of Fright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(34, "Dust 'til Dawn", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(35, "Garden Grab", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(36, "Pixel Perfect", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(37, "Slot Trot", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(38, "Gondola Glide", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(39, "Light Breeze", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(40, "Body Builder", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(41, "Mole-it!", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(42, "Cashapult", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(43, "Jump the Gun", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(44, "Rocky Road", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(45, "Clean Team", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(46, "Hyper Sniper", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(47, "Insectiride", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(48, "Sunday Drivers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(49, "Stamp By Me", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(50, "Throw Me a Bone", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(51, "Black Hole Boogie", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Full Tilt", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(53, "Sumo of Doom-o", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(54, "O-Zone", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Pitifall", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(56, "Mass Meteor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(57, "Lunar-tics", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(58, "T Minus Five", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Asteroad Rage", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(60, "Boo'd Off the Stage", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(61, "Boonanza!", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(62, "Trick or Tree", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(63, "Something's Amist", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(64, "Wrasslin' Rapids", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(65, "Verbal Assault", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(66, "Shoot Yer Mouth Off", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(67, "Talkie Walkie", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(68, "Burnstile", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(69, "Word Herd", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(70, "Fruit Talktail", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(71, "Pit Boss", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(72, "Dizzy Rotisserie", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(73, "Dark 'n Crispy", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(74, "Tally Me Banana", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(75, "Banana Shake", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(76, "Pier Factor", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(77, "Seer Terror", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(78, "Block Star", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(79, "Lab Brats", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(80, "Strawberry Shortfuse", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(81, "Control Schtick", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(82, "Dunk Bros.", MinigameCategoryConstants.EXTRA_MINIGAME),
    };

    public static final Minigame[] MARIO_PARTY_7_MINIGAMES = {
            new Minigame(1, "Catchy Tunes", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Bubble Brawl", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Track & Yield", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Fun Run", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Cointagious", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Snow Ride", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Real Smoothie", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(8, "Picture This", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Ghost in the Hall", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Big Dripper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Target Tag", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Pokey Pummel", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Take Me Ohm", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Kart Wheeled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Balloon Busters", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(16, "Clock Watchers", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(17, "Dart Attack", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(19, "Oil Crisis", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(20, "Number Crunchers", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(21, "La Bomba", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(22, "Spray Anything", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "Balloonatic", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Spinner Cell", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(25, "Think Tank", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(26, "Flashfright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(27, "Coin-op Bop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(28, "Easy Pickings", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(29, "Wheel of Woe", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(30, "Boxing Day", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(31, "Be My Chum!", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(32, "StratosFEAR!", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(33, "Pogo-a-Go-Go", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(34, "Buzzstormer", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Tile and Error", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(36, "Battery Ram", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(37, "Cardinal Rule", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(38, "Ice Moves", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(39, "Bumper Crop", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(40, "Hop-O-Matic 4000", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(41, "Wingin' It", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(42, "Sphere Factor", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(43, "Herbicidal Maniac", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(44, "Pyramid Scheme", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(45, "World Piece", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(46, "Warp Pipe Dreams", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(47, "Weight for It", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(48, "Helipopper", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(49, "Monty's Revenge", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(50, "Deck Hands", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(51, "Mad Props", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Gimme a Sign", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(53, "Bridge Work", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(54, "Spin Doctor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Hip Hop Drop", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(56, "Air Farce", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(57, "The Final Countdown", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(58, "Royal Rumpus", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Light Speed", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(60, "Apes of Wrath", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(61, "Fish & Cheeps", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(62, "Camp Ukiki", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(63, "Funstacle Course!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(64, "Funderwall!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(65, "Magmagical Journey!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(66, "Tunnel of Lava!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(67, "Treasure Dome!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(68, "Slot-O-Whirl!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(69, "Peel Out", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(70, "Bananas Faster", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(71, "Stump Change", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(72, "Jump, Man", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(73, "Vine Country", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(74, "A Bridge Too Short", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(75, "Spider Stomp", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(76, "Stick and Spin", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(77, "Synch-row-nicity", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(78, "Grin and Bar It", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(79, "Hammer Spammer", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(80, "Gimme a Brake", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(81, "Bumper to Bumper", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(82, "Spin Off", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(83, "Rope a Dope", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(84, "Duct & Cover", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(85, "Mic Space Minigame", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(86, "Bowser's Lovely Lift!", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(88, "Mathemortican", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(89, "Bob-ombic Plague", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(90, "Unhappy Trails", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(91, "Shock Absorbers", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_8_MINIGAMES = {
            new Minigame(1, "Speedy Grafitti", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Swing Kings", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(3, "Water Ski Spree", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Punch-a-Bunch", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Crank to Rank", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "At the Chomp Wash", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Mosh-Pit Playroom", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Mario Matrix", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Hammer de Pokari (Unused)", MinigameCategoryConstants.UNUSED_MINIGAME),
            new Minigame(10, "Grabby Gridiron", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(11, "Lava or Leave 'Em", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Kartastrophe", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Guru-Guru Kataduke (Unused)", MinigameCategoryConstants.UNUSED_MINIGAME),
            new Minigame(14, "Aim of the Game", MinigameCategoryConstants.BATTLE_DUEL_MINIGAME),
            new Minigame(15, "Rudder Madness", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Gun the Runner", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(17, "Grabbin' Gold", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(18, "Power Trip", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(19, "Bob-ombs Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(20, "Swervin' Skies", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(21, "Picture Perfect", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(22, "Snow Way Out", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "Thrash 'n' Crash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Chump Rope", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(25, "Sick and Twisted", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(26, "Bumper Balloons", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(27, "Rowed to Victory", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(28, "Winner or Dinner", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(29, "Paint Misbehavin'", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(30, "Sugar Rush", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(31, "King of the Thrill", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(32, "Shake It Up", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(33, "Lean, Mean Ravine", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(34, "Boo-ting Gallery", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Crops 'n' Robbers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(36, "In the Nick of Time", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(37, "Cut from the Team", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(38, "Snipe for the Picking", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(39, "Saucer Swarm", MinigameCategoryConstants.BATTLE_DUEL_MINIGAME),
            new Minigame(40, "Glacial Meltdown", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(41, "Attention Grabber", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(42, "Blazing Lassos", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(43, "Wing and a Scare", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(44, "Lob to Rob", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(45, "Pumper Cars", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(46, "Cosmic Slalom", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(47, "Lava Lobbers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(48, "Loco Motives", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(49, "Specter Inspector", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(50, "Frozen Assets", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(51, "Breakneck Building", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Surf's Way Up", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(53, "Ochiruna Rodeo (Unused)", MinigameCategoryConstants.UNUSED_MINIGAME),
            new Minigame(54, "Balancing Act", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Ion the Prize", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(56, "You're the Bob-omb", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(57, "Scooter Pursuit", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(58, "Cardiators", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Rotation Station", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(60, "Eyebrawl", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(61, "Table Menace", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(62, "Flagging Rights", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(63, "Trial by Tile", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(64, "Star Carnival Bowling", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(65, "Puzzle Pillars", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(66, "Canyon Cruisers", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(67, "Chomping Frenzy", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(68, "Settle It in Court", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(69, "Moped Mayhem", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(70, "Flip the Chimp", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(71, "Pour to Score", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(72, "Fruit Picker", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(73, "Stampede", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(74, "Superstar Showdown", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(75, "Alpine Assault", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(76, "Treacherous Tightrope", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static String[] getNames(Minigame[] minigameList) {
        String[] names = new String[minigameList.length];

        for (int i=0; i<minigameList.length; i++) {
            names[i] = minigameList[i].getName();
        }

        return names;
    }
}