package constants;

import ui.Minigame;

public class MinigameConstants {

    public static final Minigame[] MARIO_PARTY_1_MINIGAMES = {
            new Minigame(0x00, "Memory Match", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x02, "Slot Machine", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x03, "Buried Treasure", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x04, "Treasure Divers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "Shell Game", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x06, "Slot Car Derby 1", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x07, "Hot Bob-omb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x08, "Slot Car Derby 2", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x09, "Pipe Maze", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x0A, "Ghost Guess", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x0B, "Musical Mushroom", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0C, "Pedal Power", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x0D, "Crazy Cutter", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0E, "Face Lift", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0F, "Whack-a-Plant", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x10, "Bash 'n' Cash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Bowl Over", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Ground Pound", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x13, "Balloon Burst", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x14, "Coin Block Blitz", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x15, "Coin Block Bash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Skateboard Scamper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x17, "Box Mountain Mayhem", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x18, "Platform Peril", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x19, "Teetering Towers", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x1A, "Mushroom Mix-Up", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1B, "Bumper Ball Maze 1", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x1C, "Grab Bag", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1D, "Bobsled Run", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1E, "Bumper Balls", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1F, "TightRope Treachery", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x20, "Knock Block Tower", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x21, "Tipsy Tourney", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x22, "Bombs Away", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x23, "Crane Game", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x24, "Bumper Ball Maze 2", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x25, "Slot Car Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x26, "Mario Bandstand", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x27, "Desert Dash", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x28, "Shy Guy Says", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x29, "Limbo Dance", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x2A, "Bombsketball", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2B, "Cast Aways", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2C, "Key-pa-Way", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2D, "Running of the Bulb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2E, "Hot Rope Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2F, "Handcar Havoc", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x31, "Deep Sea Divers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x32, "Piranha's Pursuit", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x33, "Tug o' War", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x34, "Paddle Battle", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x35, "Bumper Ball Maze 3", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x36, "Coin Shower Flower", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x37, "Hammer Drop", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_2_MINIGAMES = {
            new Minigame(0x01, "BOWSER Slots", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x02, "Roll Out the Barrels", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x03, "Coffin Congestion", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x04, "Hammer Slammer", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x05, "Give Me a Brake!", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x06, "Mallet-Go Round", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x07, "Grab Bag", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x08, "Bumper Balloon Cars", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x09, "Rakin' 'em In", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0B, "Day at the Races", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0C, "Face Lift", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0D, "Crazy Cutters", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0E, "Hot BOB-OMB", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x0F, "Bowl Over", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x10, "Rainbow Run", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Crane Game", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Move to the Music", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x13, "BOB-OMB Barrage", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x14, "Look Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x15, "Shock Drop or Roll", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Lights Out", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x17, "Filet Relay", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x18, "Archer-ival", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1A, "TOAD Bandstand", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1B, "Bobsled Run", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1C, "Handcar Havoc", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1E, "Balloon Burst", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1F, "Sky Pilots", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x20, "Speed Hockey", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x21, "Cake Factory", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x23, "Dungeon Dash", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x24, "Magnet Carta", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x25, "Lava Tile Isle", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x26, "Hot Rope Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x27, "Shell Shocked", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x28, "TOAD in the Box", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x29, "Mecha-Marathon", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2A, "Roll Call", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2B, "Abandon Ship", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2C, "Platform Peril", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2D, "Totem Pole Pound", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2E, "Bumper Balls", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x30, "Bombs Away", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x31, "Tipsy Tourney", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x32, "Honeycomb Havoc", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x33, "Hexagon Heat", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x34, "Skateboard Scamper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x35, "Slot Car Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x36, "Shy Guy Says", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x37, "Sneak 'n' Snore", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x39, "Driver's Ed", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x3B, "Quick Draw Corks", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3C, "Saber Slashes", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3D, "Mushroom Brew", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3E, "Time Bomb", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3F, "Psychic Safari", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x40, "Rock Paper MARIO", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x41, "BOWSER's Big Blast", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x42, "Looney Lumberjacks", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x43, "Torpedo Targets", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x44, "Destruction Duet", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x45, "Dizzy Dancing", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x46, "Tile Driver", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x47, "Quicksand Cache", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x48, "Deep Sea Salvage", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_3_MINIGAMES = {
            new Minigame(0x01, "Hand, Line and Sinker", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x02, "Coconut Conk", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x03, "Spotlight Swim", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x04, "Boulder Ball", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x05, "Crazy Cogs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x06, "Hide and Sneak", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x07, "Ridiculous Relay", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x08, "Thwomp Pull", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x09, "River Raiders", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x0A, "Tidal Toss", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x0B, "Eatsa Pizza", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0C, "Baby Bowser Broadside", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0D, "Pump, Pump and Away", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0E, "Hyper Hydrants", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0F, "Picking Panic", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x10, "Cosmic Coaster", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x11, "Puddle Paddle", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x12, "Etch 'n' Catch", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x13, "Log Jam", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x14, "Slot Synch", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x15, "Treadmill Grill", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x16, "Toadstool Titan", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x17, "Aces High", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x18, "Bounce 'n' Trounce", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x19, "Ice Rink Risk", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1A, "Locked Out", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x1B, "Chip Shot Challenge", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1C, "Parasol Plummet", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1D, "Messy Memory", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1E, "Picture Imperfect", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1F, "Mario's Puzzle Party", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x20, "The Beat Goes On", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x21, "M.P.I.Q.", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x22, "Curtain Call", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x23, "Water Whirled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x24, "Frigid Bridges", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x25, "Awful Tower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x26, "Cheep Cheep Chase", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x27, "Pipe Cleaners", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x28, "Snowball Summit", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x29, "All Fired Up", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2A, "Stacked Deck", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2B, "Three Door Monty", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2C, "Rockin' Raceway", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2D, "Merry-Go-Chomp", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2E, "Slap Down", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2F, "Storm Chasers", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x30, "Eye Sore", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x31, "Vine With Me", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x32, "Popgun Pick-Off", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x33, "End of the Line", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x34, "Bowser Toss", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x35, "Baby Bowser Bonkers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x36, "Motor Rooter", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x37, "Silly Screws", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x38, "Crowd Cover", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x39, "Tick Tock Hop", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3A, "Fowl Play", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3B, "Winner's Wheel", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3C, "Hey, Batter, Batter!", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3D, "Bobbing Bow-loons", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3E, "Dorrie Dip", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x3F, "Swinging with Sharks", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x40, "Swing 'n' Swipe", MinigameCategoryConstants.ITEM_MINIGAME),
            new Minigame(0x42, "Stardust Battle", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x43, "Game Guy's Roulette", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x44, "Game Guy's Lucky 7", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x45, "Game Guy's Magic Boxes", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x46, "Game Guy's Sweet Surprise", MinigameCategoryConstants.GAME_GUY_MINIGAME),
            new Minigame(0x47, "Dizzy Dinghies", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x48, "Mario's Puzzle Party Pro", MinigameCategoryConstants.EXTRA_MINIGAME),
    };

    public static final Minigame[] MARIO_PARTY_4_MINIGAMES = {
            new Minigame(0x00, "Manta Rings", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x01, "Slime Time", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x02, "Booksquirm", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x03, "Trace Race", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x04, "Mario Medley", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "Avalanche!", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x06, "Domination", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x07, "Paratrooper Plunge", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x08, "Toad's Quick Draw", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x09, "Three Throw", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0A, "Photo Finish", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0B, "Mr. Blizzard's Brigade", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0C, "Bob-Omb Breakers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0D, "Long Claw of the Law", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0E, "Stamp Out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0F, "Candlelight Flight", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x10, "Makin' Waves", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Hide and Go BOOM!", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Tree Stomp", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x13, "Fish n' Drips", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x14, "Hop or Pop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x15, "Money Belts", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "GOOOOOOOAL!!", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x17, "Blame it on the Crane", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x18, "The Great Deflate", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x19, "Revers-a-Bomb", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1A, "Right Oar Left?", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1B, "Cliffhangers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1C, "Team Treasure Trek", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1D, "Pair-a-Sailing", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1E, "Order Up", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1F, "Dungeon Duos", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x21, "Cheep Cheep Sweep", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x22, "Darts of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x23, "Fruits of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x24, "Balloon of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x25, "Chain Chomp Fever", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x26, "Paths of Peril", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x27, "Bowser's Bigger Blast", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x28, "Butterfly Blitz", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2A, "Mario Speedwagons", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2C, "Bowser Bop", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x2D, "Mystic Match 'Em", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x2E, "Archaeologuess", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x2F, "Goomba's Chip Flip", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x30, "Kareening Koopas", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x31, "The Final Battle!", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x36, "Rumble Fishing", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x37, "Take a Breather", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x38, "Bowser Wrestling", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x39, "Panels of Doom", MinigameCategoryConstants.EXTRA_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_5_MINIGAMES = {
            new Minigame(0x00, "Coney Island", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x01, "Ground Pound Down", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x02, "Chimp Chase", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x03, "Chomp Romp", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x04, "Pushy Penguins", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "Leaf Leap", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x06, "Night Light Fright", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x07, "Pop-Star Piranhas", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x08, "Mazed & Confused", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x09, "Dinger Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0A, "Hydrostars", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0B, "Later Skater", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0C, "Will Flower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0D, "Triple Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0E, "Hotel Goomba", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0F, "Coin Cache", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x10, "Flatiator", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Squared Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Mario Mechs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x13, "Revolving Fire", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x14, "Clock Stoppers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x15, "Heat Stroke", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Beam Team", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x17, "Vicious Vending", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x18, "Big Top Drop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x19, "Defuse or Lose", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1A, "ID UFO", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1B, "Mario Can-Can", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1C, "Handy Hoppers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1D, "Berry Basket", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1E, "Bus Buffer", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1F, "Rumble Ready", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x20, "Submarathon", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x21, "Manic Mallets", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x22, "Astro-Logical", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x23, "Bill Blasters", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x24, "Tug-o-Dorrie", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x25, "Twist 'n' Out", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x26, "Lucky Lineup", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x27, "Random Ride", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x28, "Shock Absorbers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x29, "Countdown Pound", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2A, "Whomp Maze", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2B, "Shy Guy Showdown", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2C, "Button Mashers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2D, "Get a Rope", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2E, "Pump 'n' Jump", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2F, "Head Waiter", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x30, "Blown Away", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x31, "Merry Poppings", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x32, "Pound Peril", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x33, "Piece Out", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x34, "Bound of Music", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x35, "Wind Wavers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x36, "Sky Survivor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3A, "Rain of Fire", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x3B, "Cage-in Cookin'", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x3C, "Scaldin' Cauldron", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x3D, "Frightmare", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x3E, "Flower Shower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x3F, "Dodge Bomb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x40, "Fish Upon a Star", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x41, "Rumble Fumble", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x42, "Quilt for Speed", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x43, "Tube It or Lose It", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x44, "Mathletes", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x45, "Fight Cards", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x46, "Banana Punch", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x47, "Da Vine Climb", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x48, "Mass A-peel", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x49, "Panic Pinball", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x4A, "Banking Coins", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x4B, "Frozen Frenzy", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x4C, "Curvy Curbs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x4E, "Fish Sticks", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_6_MINIGAMES = {
            new Minigame(0x00, "Smashdance", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x01, "Odd Card Out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x02, "Freeze Frame", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x03, "What Goes Up...", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x04, "Granite Getaway", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "Circuit Maximus", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x06, "Catch You Letter", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x07, "Snow Whirled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x08, "Daft Rafts", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x09, "Tricky Tires", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0A, "Treasure Trawlers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0B, "Memory Lane", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0C, "Mowtown", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0D, "Cannonball Fun", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0E, "Note to Self", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0F, "Same is Lame", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x10, "Light Up My Night", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x11, "Lift Leapers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x12, "Blooper Scooper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x13, "Trap Ease Artist", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x14, "Pokey Punch-out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x15, "Money Belt", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x16, "Cash Flow", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x17, "Cog Jog", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x18, "Sink or Swim", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x19, "Snow Brawl", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1A, "Ball Dozers", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1B, "Surge and Destroy", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1C, "Pop Star", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1D, "Stage Fright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1E, "Conveyor Bolt", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1F, "Crate and Peril", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x20, "Ray of Fright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x21, "Dust 'til Dawn", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x22, "Garden Grab", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x23, "Pixel Perfect", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x24, "Slot Trot", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x25, "Gondola Glide", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x26, "Light Breeze", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x27, "Body Builder", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x28, "Mole-it!", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x29, "Cashapult", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2A, "Jump the Gun", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2B, "Rocky Road", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2C, "Clean Team", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2D, "Hyper Sniper", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2E, "Insectiride", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x2F, "Sunday Drivers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x30, "Stamp By Me", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x31, "Throw Me a Bone", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x32, "Black Hole Boogie", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x33, "Full Tilt", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x34, "Sumo of Doom-o", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x35, "O-Zone", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x36, "Pitifall", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x37, "Mass Meteor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x38, "Lunar-tics", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x39, "T Minus Five", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3A, "Asteroad Rage", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3B, "Boo'd Off the Stage", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3C, "Boonanza!", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3D, "Trick or Tree", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3E, "Something's Amist", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3F, "Wrasslin' Rapids", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x40, "Verbal Assault", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x41, "Shoot Yer Mouth Off", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x42, "Talkie Walkie", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x43, "Burnstile", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x44, "Word Herd", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x45, "Fruit Talktail", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x46, "Pit Boss", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x47, "Dizzy Rotisserie", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x48, "Dark 'n Crispy", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x49, "Tally Me Banana", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x4A, "Banana Shake", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x4B, "Pier Factor", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x4C, "Seer Terror", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x4D, "Block Star", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x4E, "Lab Brats", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x4F, "Strawberry Shortfuse", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x50, "Control Schtick", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x51, "Dunk Bros.", MinigameCategoryConstants.EXTRA_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_7_MINIGAMES = {
            new Minigame(0x00, "Catchy Tunes", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x01, "Bubble Brawl", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x02, "Track & Yield", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x03, "Fun Run", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x04, "Cointagious", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "Snow Ride", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x06, "Real Smoothie", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x07, "Picture This", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x08, "Ghost in the Hall", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x09, "Big Dripper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0A, "Target Tag", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0B, "Pokey Pummel", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0C, "Take Me Ohm", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0D, "Kart Wheeled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0E, "Balloon Busters", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(0x0F, "Clock Watchers", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(0x10, "Dart Attack", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(0x12, "Oil Crisis", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(0x13, "Number Crunchers", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x14, "La Bomba", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x15, "Spray Anything", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Balloonatic", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x17, "Spinner Cell", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x18, "Think Tank", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x19, "Flashfright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1A, "Coin-op Bop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1B, "Easy Pickings", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x1C, "Wheel of Woe", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x1D, "Boxing Day", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x1E, "Be My Chum!", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x1F, "StratosFEAR!", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(0x20, "Pogo-a-Go-Go", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x21, "Buzzstormer", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x22, "Tile and Error", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x23, "Battery Ram", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x24, "Cardinal Rule", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x25, "Ice Moves", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x26, "Bumper Crop", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x27, "Hop-O-Matic 4000", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x28, "Wingin' It", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x29, "Sphere Factor", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2A, "Herbicidal Maniac", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2B, "Pyramid Scheme", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2C, "World Piece", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2D, "Warp Pipe Dreams", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2E, "Weight for It", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2F, "Helipopper", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x30, "Monty's Revenge", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x31, "Deck Hands", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x32, "Mad Props", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x33, "Gimme a Sign", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x34, "Bridge Work", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x35, "Spin Doctor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x36, "Hip Hop Drop", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x37, "Air Farce", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x38, "The Final Countdown", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x39, "Royal Rumpus", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3A, "Light Speed", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3B, "Apes of Wrath", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3C, "Fish & Cheeps", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3D, "Camp Ukiki", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3E, "Funstacle Course!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x3F, "Funderwall!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x40, "Magmagical Journey!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(0x41, "Tunnel of Lava!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(0x42, "Treasure Dome!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(0x43, "Slot-O-Whirl!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(0x44, "Peel Out", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x45, "Bananas Faster", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x46, "Stump Change", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(0x47, "Jump, Man", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(0x48, "Vine Country", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(0x49, "A Bridge Too Short", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(0x4A, "Spider Stomp", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x4B, "Stick and Spin", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x4C, "Synch-row-nicity", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x4D, "Grin and Bar It", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x4E, "Hammer Spammer", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x4F, "Gimme a Brake", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x50, "Bumper to Bumper", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x51, "Spin Off", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x52, "Rope a Dope", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x53, "Duct & Cover", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x54, "Mic Space Minigame", MinigameCategoryConstants.EXTRA_MINIGAME),
            new Minigame(0x55, "Bowser's Lovely Lift!", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x57, "Mathemortican", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(0x58, "Bob-ombic Plague", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x59, "Unhappy Trails", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(0x5A, "Shock Absorbers", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_8_MINIGAMES = {
            new Minigame(0x00, "Speedy Grafitti", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x01, "Swing Kings", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(0x02, "Water Ski Spree", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x03, "Punch-a-Bunch", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x04, "Crank to Rank", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "At the Chomp Wash", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x06, "Mosh-Pit Playroom", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x07, "Mario Matrix", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x09, "Grabby Gridiron", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x0A, "Lava or Leave 'Em", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0B, "Kartastrophe", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0D, "Aim of the Game", MinigameCategoryConstants.BATTLE_DUEL_MINIGAME),
            new Minigame(0x0E, "Rudder Madness", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0F, "Gun the Runner", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x10, "Grabbin' Gold", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Power Trip", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Bob-ombs Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x13, "Swervin' Skies", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x14, "Picture Perfect", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x15, "Snow Way Out", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Thrash 'n' Crash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x17, "Chump Rope", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x18, "Sick and Twisted", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x19, "Bumper Balloons", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(0x1A, "Rowed to Victory", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1B, "Winner or Dinner", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1C, "Paint Misbehavin'", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(0x1D, "Sugar Rush", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(0x1E, "King of the Thrill", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1F, "Shake It Up", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(0x20, "Lean, Mean Ravine", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x21, "Boo-ting Gallery", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x22, "Crops 'n' Robbers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x23, "In the Nick of Time", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x24, "Cut from the Team", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x25, "Snipe for the Picking", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x26, "Saucer Swarm", MinigameCategoryConstants.BATTLE_DUEL_MINIGAME),
            new Minigame(0x27, "Glacial Meltdown", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(0x28, "Attention Grabber", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x29, "Blazing Lassos", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2A, "Wing and a Scare", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2B, "Lob to Rob", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2C, "Pumper Cars", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2D, "Cosmic Slalom", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2E, "Lava Lobbers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x2F, "Loco Motives", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x30, "Specter Inspector", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x31, "Frozen Assets", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x32, "Breakneck Building", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x33, "Surf's Way Up", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x35, "Balancing Act", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x36, "Ion the Prize", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x37, "You're the Bob-omb", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x38, "Scooter Pursuit", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x39, "Cardiators", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3A, "Rotation Station", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x3B, "Eyebrawl", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x43, "Settle It in Court", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(0x45, "Flip the Chimp", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(0x46, "Pour to Score", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x47, "Fruit Picker", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x48, "Stampede", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x49, "Superstar Showdown", MinigameCategoryConstants.STORY_MINIGAME),
            new Minigame(0x4A, "Alpine Assault", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x4B, "Treacherous Tightrope", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static String[] getNames(Minigame[] minigameList) {
        String[] names = new String[minigameList.length];

        for (int i=0; i<minigameList.length; i++) {
            names[i] = minigameList[i].getName();
        }

        return names;
    }
}