package constants;

import ui.Minigame;

public class MinigameConstants {

    public static final Minigame[] MARIO_PARTY_1_MINIGAMES = {
            new Minigame(0x00, "Memory Match", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x02, "Slot Machine", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x03, "Buried Treasure", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x04, "Treasure Divers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x05, "Shell Game", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x06, "Slot Car Derby 1", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x07, "Hot Bob-omb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x08, "Slot Car Derby 2", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x09, "Pipe Maze", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x0A, "Ghost Guess", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x0B, "Musical Mushroom", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0C, "Pedal Power", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x0D, "Crazy Cutter", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0E, "Face Lift", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x0F, "Whack-a-Plant", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x10, "Bash 'n' Cash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x11, "Bowl Over", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x12, "Ground Pound", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x13, "Balloon Burst", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x14, "Coin Block Blitz", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x15, "Coin Block Bash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x16, "Skateboard Scamper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x17, "Box Mountain Mayhem", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x18, "Platform Peril", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x19, "Teetering Towers", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x1A, "Mushroom Mix-Up", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1C, "Grab Bag", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1D, "Bobsled Run", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x1E, "Bumper Balls", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x1F, "TightRope Treachery", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x20, "Knock Block Tower", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x21, "Tipsy Tourney", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x22, "Bombs Away", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x23, "Crane Game", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x25, "Slot Car Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x26, "Mario Bandstand", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x27, "Desert Dash", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x28, "Shy Guy Says", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x29, "Limbo Dance", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(0x2A, "Bombsketball", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x2B, "Cast Aways", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2C, "Key-pa-Way", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2D, "Running of the Bulb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2E, "Hot Rope Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(0x2F, "Handcar Havoc", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x31, "Deep Sea Divers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(0x32, "Piranha's Pursuit", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x33, "Tug o' War", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x34, "Paddle Battle", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x36, "Coin Shower Flower", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(0x37, "Hammer Drop", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_4_MINIGAMES = {
            new Minigame(1, "Manta Rings", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Slime Time", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Booksquirm", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Trace Race", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(5, "Mario Medley", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Avalanche!", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Domination", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Paratrooper Plunge", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Toad's Quick Draw", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Three Throw", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Photo Finish", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Mr. Blizzard's Brigade", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Bob-Omb Breakers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Long Claw of the Law", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Stamp Out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Candlelight Flight", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(17, "Makin' Waves", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(18, "Hide and Go BOOM!", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(19, "Tree Stomp", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(20, "Fish n' Drips", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(21, "Hop or Pop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(22, "Money Belts", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "GOOOOOOOAL!!", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Blame it on the Crane", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(25, "The Great Deflate", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(26, "Revers-a-Bomb", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(27, "Right Oar Left?", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(28, "Cliffhangers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(29, "Team Treasure Trek", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(30, "Pair-a-Sailing", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(31, "Order Up", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(32, "Dungeon Duos", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(34, "Cheep Cheep Sweep", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Darts of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(36, "Fruits of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(37, "Balloon of Doom", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(38, "Chain Chomp Fever", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(39, "Paths of Peril", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(40, "Bowser's Bigger Blast", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(41, "Butterfly Blitz", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(43, "Mario Speedwagons", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(55, "Rumble Fishing", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(56, "Take a Breather", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_5_MINIGAMES = {
            new Minigame(1, "Coney Island", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Ground Pound Down", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Chimp Chase", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Chomp Romp", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Pushy Penguins", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Leaf Leap", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Night Light Fright", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Pop-Star Piranhas", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Mazed & Confused", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Dinger Derby", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Hydrostars", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Later Skater", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Will Flower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Triple Jump", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Hotel Goomba", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Coin Cache", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(17, "Flatiator", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(18, "Squared Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(19, "Mario Mechs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(20, "Revolving Fire", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(21, "Clock Stoppers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(22, "Heat Stroke", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "Beam Team", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Vicious Vending", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(25, "Big Top Drop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(26, "Defuse or Lose", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(27, "ID UFO", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(28, "Mario Can-Can", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(29, "Handy Hoppers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(30, "Berry Basket", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(31, "Bus Buffer", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(32, "Rumble Ready", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(33, "Submarathon", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(34, "Manic Mallets", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Astro-Logical", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(36, "Bill Blasters", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(37, "Tug-o-Dorrie", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(38, "Twist 'n' Out", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(39, "Lucky Lineup", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(40, "Random Ride", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(41, "Shock Absorbers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(42, "Countdown Pound", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(43, "Whomp Maze", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(44, "Shy Guy Showdown", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(45, "Button Mashers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(46, "Get a Rope", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(47, "Pump 'n' Jump", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(48, "Head Waiter", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(49, "Blown Away", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(50, "Merry Poppings", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(51, "Pound Peril", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Piece Out", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(53, "Bound of Music", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(54, "Wind Wavers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Sky Survivor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Rain of Fire", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(60, "Cage-in Cookin'", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(61, "Scaldin' Cauldron", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(63, "Flower Shower", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(64, "Dodge Bomb", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(65, "Fish Upon a Star", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(66, "Rumble Fumble", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(67, "Quilt for Speed", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(68, "Tube It or Lose It", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(69, "Mathletes", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(70, "Fight Cards", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(71, "Banana Punch", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(72, "Da Vine Climb", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(73, "Mass A-peel", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(74, "Panic Pinball", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(75, "Banking Coins", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(76, "Frozen Frenzy", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(77, "Curvy Curbs", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(79, "Fish Sticks", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_6_MINIGAMES = {
            new Minigame(1, "Smashdance", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Odd Card Out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Freeze Frame", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "What Goes Up...", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Granite Getaway", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Circuit Maximus", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Catch You Letter", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Snow Whirled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Daft Rafts", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Tricky Tires", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Treasure Trawlers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Memory Lane", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Mowtown", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Cannonball Fun", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Note to Self", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Same is Lame", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(17, "Light Up My Night", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(18, "Lift Leapers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(19, "Blooper Scooper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(20, "Trap Ease Artist", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(21, "Pokey Punch-out", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(22, "Money Belt", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(23, "Cash Flow", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Cog Jog", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(25, "Sink or Swim", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(26, "Snow Brawl", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(27, "Ball Dozers", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(28, "Surge and Destroy", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(29, "Pop Star", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(30, "Stage Fright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(31, "Conveyor Bolt", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(32, "Crate and Peril", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(33, "Ray of Fright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(34, "Dust 'til Dawn", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(35, "Garden Grab", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(36, "Pixel Perfect", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(37, "Slot Trot", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(38, "Gondola Glide", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(39, "Light Breeze", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(40, "Body Builder", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(41, "Mole-it!", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(42, "Cashapult", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(43, "Jump the Gun", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(44, "Rocky Road", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(45, "Clean Team", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(46, "Hyper Sniper", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(47, "Insectiride", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(48, "Sunday Drivers", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(49, "Stamp By Me", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(50, "Throw Me a Bone", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(51, "Black Hole Boogie", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Full Tilt", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(53, "Sumo of Doom-o", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(54, "O-Zone", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Pitifall", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(56, "Mass Meteor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(57, "Lunar-tics", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(58, "T Minus Five", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Asteroad Rage", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(60, "Boo'd Off the Stage", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(61, "Boonanza!", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(62, "Trick or Tree", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(63, "Something's Amist", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(64, "Wrasslin' Rapids", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(65, "Verbal Assault", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(66, "Shoot Yer Mouth Off", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(67, "Talkie Walkie", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(68, "Burnstile", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(69, "Word Herd", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(70, "Fruit Talktail", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(71, "Pit Boss", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(72, "Dizzy Rotisserie", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(73, "Dark 'n Crispy", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(74, "Tally Me Banana", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(75, "Banana Shake", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(76, "Pier Factor", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(80, "Strawberry Shortfuse", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(81, "Control Schtick", MinigameCategoryConstants.BATTLE_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_7_MINIGAMES = {
            new Minigame(1, "Catchy Tunes", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Bubble Brawl", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(3, "Track & Yield", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Fun Run", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Cointagious", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "Snow Ride", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Real Smoothie", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(8, "Picture This", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(9, "Ghost in the Hall", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Big Dripper", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(11, "Target Tag", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Pokey Pummel", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(13, "Take Me Ohm", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Kart Wheeled", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(15, "Balloon Busters", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(16, "Clock Watchers", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(17, "Dart Attack", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(19, "Oil Crisis", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(20, "Number Crunchers", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(21, "La Bomba", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(22, "Spray Anything", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "Balloonatic", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Spinner Cell", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(25, "Think Tank", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(26, "Flashfright", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(27, "Coin-op Bop", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(28, "Easy Pickings", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(29, "Wheel of Woe", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(30, "Boxing Day", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(31, "Be My Chum!", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(32, "StratosFEAR!", MinigameCategoryConstants.ONE_V_THREE_MIC_MINIGAME),
            new Minigame(33, "Pogo-a-Go-Go", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(34, "Buzzstormer", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Tile and Error", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(36, "Battery Ram", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(37, "Cardinal Rule", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(39, "Bumper Crop", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(40, "Hop-O-Matic 4000", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(41, "Wingin' It", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(42, "Sphere Factor", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(43, "Herbicidal Maniac", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(44, "Pyramid Scheme", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(45, "World Piece", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(46, "Warp Pipe Dreams", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(47, "Weight for It", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(48, "Helipopper", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(49, "Monty's Revenge", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(50, "Deck Hands", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(51, "Mad Props", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Gimme a Sign", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(53, "Bridge Work", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(54, "Spin Doctor", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Hip Hop Drop", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(56, "Air Farce", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(57, "The Final Countdown", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(58, "Royal Rumpus", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Light Speed", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(60, "Apes of Wrath", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(61, "Fish & Cheeps", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(62, "Camp Ukiki", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(63, "Funstacle Course!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(64, "Funderwall!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(65, "Magmagical Journey!", MinigameCategoryConstants.BOWSER_MINIGAME),
            new Minigame(66, "Tunnel of Lava!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(67, "Treasure Dome!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(68, "Slot-O-Whirl!", MinigameCategoryConstants.ONE_PLAYER_BOWSER_MINIGAME),
            new Minigame(69, "Peel Out", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(70, "Bananas Faster", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(71, "Stump Change", MinigameCategoryConstants.DK_MINIGAME),
            new Minigame(72, "Jump, Man", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(73, "Vine Country", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(74, "A Bridge Too Short", MinigameCategoryConstants.ONE_PLAYER_DK_MINIGAME),
            new Minigame(75, "Spider Stomp", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(77, "Synch-row-nicity", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(78, "Grin and Bar It", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(79, "Hammer Spammer", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(80, "Gimme a Brake", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(81, "Bumper to Bumper", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(82, "Spin Off", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(83, "Rope a Dope", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(84, "Duct & Cover", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(88, "Mathemortican", MinigameCategoryConstants.FOUR_PLAYER_MIC_MINIGAME),
            new Minigame(89, "Bob-ombic Plague", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(90, "Unhappy Trails", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME),
            new Minigame(91, "Shock Absorbers", MinigameCategoryConstants.EIGHT_PLAYER_MINIGAME)
    };

    public static final Minigame[] MARIO_PARTY_8_MINIGAMES = {
            new Minigame(1, "Speedy Grafitti", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(2, "Swing Kings", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(3, "Water Ski Spree", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(4, "Punch-a-Bunch", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(5, "Crank to Rank", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(6, "At the Chomp Wash", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(7, "Mosh-Pit Playroom", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(8, "Mario Matrix", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(10, "Grabby Gridiron", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(11, "Lava or Leave 'Em", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(12, "Kartastrophe", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(14, "Aim of the Game", MinigameCategoryConstants.BATTLE_DUEL_MINIGAME),
            new Minigame(15, "Rudder Madness", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(16, "Gun the Runner", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(17, "Grabbin' Gold", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(18, "Power Trip", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(19, "Bob-ombs Away", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(20, "Swervin' Skies", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(21, "Picture Perfect", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(22, "Snow Way Out", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(23, "Thrash 'n' Crash", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(24, "Chump Rope", MinigameCategoryConstants.ONE_V_THREE_MINIGAME),
            new Minigame(25, "Sick and Twisted", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(26, "Bumper Balloons", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(27, "Rowed to Victory", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(28, "Winner or Dinner", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(29, "Paint Misbehavin'", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(30, "Sugar Rush", MinigameCategoryConstants.TWO_V_TWO_DUEL_MINIGAME),
            new Minigame(31, "King of the Thrill", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(32, "Shake It Up", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(33, "Lean, Mean Ravine", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(34, "Boo-ting Gallery", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(35, "Crops 'n' Robbers", MinigameCategoryConstants.TWO_V_TWO_MINIGAME),
            new Minigame(36, "In the Nick of Time", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(37, "Cut from the Team", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(38, "Snipe for the Picking", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(39, "Saucer Swarm", MinigameCategoryConstants.BATTLE_DUEL_MINIGAME),
            new Minigame(40, "Glacial Meltdown", MinigameCategoryConstants.BATTLE_MINIGAME),
            new Minigame(41, "Attention Grabber", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(42, "Blazing Lassos", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(43, "Wing and a Scare", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(44, "Lob to Rob", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(45, "Pumper Cars", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(46, "Cosmic Slalom", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(47, "Lava Lobbers", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(48, "Loco Motives", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(49, "Specter Inspector", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(50, "Frozen Assets", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(51, "Breakneck Building", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(52, "Surf's Way Up", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(54, "Balancing Act", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(55, "Ion the Prize", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(56, "You're the Bob-omb", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(57, "Scooter Pursuit", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(58, "Cardiators", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(59, "Rotation Station", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(60, "Eyebrawl", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(68, "Settle It in Court", MinigameCategoryConstants.DUEL_MINIGAME),
            new Minigame(70, "Flip the Chimp", MinigameCategoryConstants.FOUR_PLAYER_DUEL_MINIGAME),
            new Minigame(71, "Pour to Score", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(72, "Fruit Picker", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(73, "Stampede", MinigameCategoryConstants.ONE_PLAYER_MINIGAME),
            new Minigame(75, "Alpine Assault", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME),
            new Minigame(76, "Treacherous Tightrope", MinigameCategoryConstants.FOUR_PLAYER_MINIGAME)
    };

    public static String[] getNames(Minigame[] minigameList) {
        String[] names = new String[minigameList.length];

        for (int i=0; i<minigameList.length; i++) {
            names[i] = minigameList[i].getName();
        }

        return names;
    }
}